- name: Test
  hosts: cumulus
  gather_facts: false

  tasks:
      - name: Set system pre-login message
        nvue_cli:
          commands:
          - set system message pre-login "{{ MSG }}"
          apply: true
          assume_yes: true